FROM nginx:1.27-alpine

COPY --chmod=0644 nginx.local.conf /etc/nginx/conf.d/default.conf
COPY --chmod=0644 maquillaje-sena-v3.html /usr/share/nginx/html/index.html
COPY --chmod=0644 manifest.webmanifest icon.svg sw.js /usr/share/nginx/html/

EXPOSE 80
