FROM nginx:1.27-alpine

COPY nginx.local.conf /etc/nginx/conf.d/default.conf
COPY maquillaje-sena-v3.html /usr/share/nginx/html/index.html
COPY manifest.webmanifest icon.svg sw.js /usr/share/nginx/html/

EXPOSE 80
